version: '3.8'

services:
  mysqldb:
    container_name: db
    hostname: db
    image: mysql:8.0.30
    restart: always
    networks:
      - mysql-net
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  among-api:
    container_name: backend
    depends_on:
      - mysqldb
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - 3065:3065
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    networks:
      - mysql-net
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  mysql-net:
    name: mysql-net